# Use an existing docker image as a base.
FROM node:alpine
WORKDIR /usr/app
# C:/Users/kenbusse/AppData/Local/DockerImageWork
COPY package.json .

# Download and install a dependency.
RUN npm install
COPY . .

# Tell the image what to do when it starts as a container.
CMD ["npm", "run", "start"]